

CREATE TABLE DEPARTMENT (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE USER_CRUD (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    DEPARTMENT_ID BIGINT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);


CREATE SEQUENCE USER_CRUD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1;